# -*- coding: utf-8 -*-
"""Untitled43.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qsoOO1dN6r0b8H7shiRo3DYD-M-QoEdM
"""



"""# Task
Perform exploratory data analysis (EDA) on the dataset "test.csv".

## Load the data

### Subtask:
Load the `test.csv` dataset into a pandas DataFrame and display the first few rows and the columns and their data types to get a sense of the data.

**Reasoning**:
Load the data into a pandas DataFrame and display the first few rows and the columns and their data types.
"""

import pandas as pd

df = pd.read_csv('test.csv')
display(df.head())
df.info()

"""## Summarize the data

### Subtask:
Display descriptive statistics for the numerical columns and the value counts for the categorical columns to understand the distribution of the data.

**Reasoning**:
Generate descriptive statistics for numerical columns and value counts for categorical columns as requested in the instructions.
"""

display(df.describe())

for column in df.columns:
    if df[column].dtype == 'object':
        print(f"Value counts for column: {column}")
        display(df[column].value_counts())

"""## Check for missing values

### Subtask:
Identify and visualize any missing values in the dataset to determine how to handle them.

**Reasoning**:
Calculate the sum of missing values for each column and visualize them using a bar plot.
"""

import matplotlib.pyplot as plt
import seaborn as sns

missing_values = df.isnull().sum()
missing_values = missing_values[missing_values > 0]

if not missing_values.empty:
    plt.figure(figsize=(10, 6))
    sns.barplot(x=missing_values.index, y=missing_values.values)
    plt.title('Number of Missing Values per Column')
    plt.xlabel('Columns')
    plt.ylabel('Number of Missing Values')
    plt.xticks(rotation=45, ha='right')
    plt.tight_layout()
    plt.show()
else:
    print("No missing values found in the dataset.")

"""## Visualize the data

### Subtask:
Create some visualizations to explore the relationships between variables and identify any patterns or anomalies.

**Reasoning**:
Create various plots to visualize the distributions of individual features and relationships between features as per the instructions.
"""

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(15, 10))

# 1. Histogram of 'Age'
plt.subplot(2, 3, 1)
sns.histplot(df['Age'].dropna(), kde=True)
plt.title('Distribution of Age')

# 2. Bar plot of 'Sex'
plt.subplot(2, 3, 2)
sns.countplot(x='Sex', data=df)
plt.title('Distribution of Gender')

# 3. Bar plot of 'Pclass'
plt.subplot(2, 3, 3)
sns.countplot(x='Pclass', data=df)
plt.title('Distribution of Passenger Class')

# 4. Scatter plot of 'Fare' vs 'Age'
plt.subplot(2, 3, 4)
sns.scatterplot(x='Age', y='Fare', data=df)
plt.title('Fare vs Age')

# 5. Box plot of 'Fare' grouped by 'Pclass'
plt.subplot(2, 3, 5)
sns.boxplot(x='Pclass', y='Fare', data=df)
plt.title('Fare Distribution by Passenger Class')

# 6. Adjust layout
plt.tight_layout()

# 7. Display plots
plt.show()

"""## Summary:

### Data Analysis Key Findings

*   The dataset contains 418 entries and 11 columns, including numerical and categorical data types.
*   Missing values are present in the 'Age', 'Fare', and 'Cabin' columns. Specifically, 'Cabin' has the most missing values, followed by 'Age', and then 'Fare'.
*   The descriptive statistics show the range and distribution for numerical columns like 'PassengerId', 'Pclass', 'Age', 'SibSp', 'Parch', and 'Fare'.
*   Value counts for categorical columns ('Name', 'Sex', 'Ticket', 'Cabin', 'Embarked') reveal the frequency of unique entries in these fields.
*   Visualizations indicate the distribution of 'Age' (with a peak around young adulthood), the distribution of 'Sex' (more males than females), and the distribution of 'Pclass' (most passengers in Pclass 3).
*   The scatter plot of 'Fare' vs 'Age' does not show a strong linear relationship.
*   The box plot of 'Fare' by 'Pclass' suggests that passengers in higher classes (Pclass 1) generally paid higher fares than those in lower classes (Pclass 2 and 3).

### Insights or Next Steps

*   Missing values in 'Age', 'Fare', and 'Cabin' need to be addressed through imputation or removal before further modeling.
*   Further exploration into the relationship between 'Fare' and 'Pclass' could be beneficial, potentially investigating outliers in fare within each class.

"""